packages:
  - frontend

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - chromedriver
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver
  - vue-demi
