name: allisons-portfolio-frontend
region: nyc
services:
  - name: nuxt-frontend
    github:
      repo: alliecatowo/portfolio
      branch: deploy/digital-ocean
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: Dockerfile
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NUXT_PUBLIC_API_URL
        scope: RUN_TIME
        value: https://allisons-portfolio-directus-9vxdi.ondigitalocean.app
      - key: NUXT_PUBLIC_DIRECTUS_TOKEN
        scope: RUN_TIME
        value: 2eEMQA40l35OBtWNH6nDS166k0o800sb
      - key: NODE_OPTIONS
        scope: RUN_TIME
        value: --no-warnings
    instance_count: 1
    instance_size_slug: basic-xs
    cors:
      allow_origins:
        - regex: ".*"
      allow_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      expose_headers:
        - Content-Length
      max_age: "86400s"
      allow_credentials: true
domains:
  - domain: allisons.dev
    type: PRIMARY
  - domain: www.allisons.dev
    type: ALIAS
