domains:
  - domain: allisons.dev
    type: PRIMARY
    zone: allisons.dev
name: allisons-portfolio-frontend
region: sfo
services:
  - name: frontend
    build_command: npm install --no-save @rollup/rollup-linux-x64-gnu && npm run build
    environment_slug: node-js
    github:
      branch: fix/portfolio-optimization
      repo: alliecatowo/portfolio
    source_dir: frontend
    run_command: npm run start
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: SERVER_PRESET
        scope: RUN_TIME
        value: digital-ocean
      - key: NITRO_PRESET
        scope: BUILD_TIME
        value: digital-ocean
      - key: NUXT_PUBLIC_DIRECTUS_URL
        scope: RUN_TIME
        value: https://directus.allisons.dev
      - key: NUXT_PUBLIC_DIRECTUS_TOKEN
        scope: RUN_TIME
        value: 2eEMQA40l35OBtWNH6nDS166k0o800sb
      - key: DEV_SITE_URL
        scope: RUN_TIME
        value: https://allisons.dev
      - key: TATTOO_SITE_URL
        scope: RUN_TIME
        value: https://tattoo.allisons.dev
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
