version: '3.8'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'Admin123!'
      PUBLIC_URL: 'https://directus.yourdomain.com'  # This will be updated with your DO URL
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'https://allisons.dev'  # Your frontend domain
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'

  database:
    image: postgres:14
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

volumes:
  database:
  uploads:
  extensions: 