name: allisons-portfolio-directus
region: nyc
services:
  - dockerfile_path: Dockerfile
    name: directus
    image:
      registry_type: DOCKER_HUB
      registry: directus
      repository: directus
      tag: 11.5.1
    source_dir: directus
    http_port: 8055
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: KEY
        scope: RUN_TIME
        value: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      - key: SECRET
        scope: RUN_TIME
        value: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      - key: ADMIN_EMAIL
        scope: RUN_TIME
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        value: "Admin123!"
      - key: DB_CLIENT
        scope: RUN_TIME
        value: "pg"
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db.PORT}
      - key: DB_USER
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${db.PASSWORD}
      - key: DB_DATABASE
        scope: RUN_TIME
        value: ${db.DATABASE}
      - key: DB_SSL
        scope: RUN_TIME
        value: "true"
      - key: DB_SSL__REJECT_UNAUTHORIZED
        scope: RUN_TIME
        value: "false"
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        scope: RUN_TIME
        value: "0"
      - key: PUBLIC_URL
        scope: RUN_TIME
        value: "https://allisons-portfolio-directus-9vxdi.ondigitalocean.app"
      - key: CORS_ENABLED
        value: "true"
        scope: RUN_TIME
      - key: CORS_ORIGIN
        value: "https://allisons.dev,https://portfolio-ismolrarb-alliecatowos-projects.vercel.app"
        scope: RUN_TIME
      - key: CORS_METHODS
        value: "GET,POST,PATCH,DELETE"
        scope: RUN_TIME
      - key: CORS_ALLOWED_HEADERS
        value: "Content-Type,Authorization"
        scope: RUN_TIME
      - key: CORS_EXPOSED_HEADERS
        value: "Content-Range"
        scope: RUN_TIME
      - key: CORS_CREDENTIALS
        value: "true"
        scope: RUN_TIME
      - key: STORAGE_LOCATIONS
        value: "local"
        scope: RUN_TIME

databases:
  - name: db
    engine: PG
    production: false
