name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Install tools
        run: mise install
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint commits
        run: pnpm exec commitlint --from=origin/${{ github.base_ref }} --to=HEAD
