name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise (Node, pnpm)
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Install tools via mise
        run: mise install

      - name: Authenticate to Google Cloud
        if: vars.USE_FIREBASE_CLI == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Firebase App Hosting Staging
        if: vars.USE_FIREBASE_CLI == 'true'
        run: |
          pnpm dlx firebase-tools apphosting:rollouts:create portfolio-staging \
            --git-branch=main \
            --force \
            --project=allie-portfolio-project

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Staging deployment triggered! Check https://portfolio-staging--portfolio-c1306.us-central1.hosted.app'
            })
