name: Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Install Firebase CLI
        run: pnpm dlx firebase-tools --version

      - name: Delete preview channel
        env:
          CHANNEL_ID: pr-${{ github.event.pull_request.number }}
          PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID || 'portfolio-c1306' }}
        run: |
          pnpm dlx firebase-tools hosting:channel:delete "$CHANNEL_ID" --project "$PROJECT_ID" --force || true

